#include "include/backend/cpu_code.hpp"
#include "include/utility/logger.hpp"

#include <fstream>
#include <sstream>
#include <algorithm>
#include <cassert>

namespace seecpp::backend {

// =============================================================================
// Public entry point
// =============================================================================

std::expected<void, CodegenError>
CpuCCodegenTarget::emit(const sir::Block&            block,
                         const BufferAllocation&      allocation,
                         const utility::WeightBuffer& weights) {

    std::filesystem::create_directories(output_dir_);

    // --- model.c ---
    {
        std::ofstream src(output_dir_ / "model.c");
        if (!src)
            return std::unexpected(CodegenError{
                "codegen", "Cannot open model.c for writing"});

        // File prologue — includes and generated marker.
        src << "/* AUTO-GENERATED by SeeC++ CpuCCodegenTarget — DO NOT EDIT */\n"
            << "#include <stddef.h>\n"
            << "#include <string.h>\n"
            << "#include <math.h>\n"
            << "#include <cblas.h>\n"
            << "#include \"model.h\"\n\n";

        // Static im2col helper used by all conv lowered ops.
        emitIm2ColHelper(src);

        // Function signature.
        src << "void seecpp_run_model(\n"
            << "    const float* const* inputs,\n"
            << "    float**             outputs,\n"
            << "    void*               arena,\n"
            << "    const void*         weight_blob)\n"
            << "{\n";

        // Declare all Value pointers.
        src << "    /* --- Value pointer declarations --- */\n";
        for (const auto& [v, slot] : allocation) {
            emitValuePtr(src, v, allocation, "arena", "weight_blob");
        }
        src << "\n";

        // Copy graph inputs from the `inputs` array into their arena slots.
        {
            int input_idx = 0;
            for (const auto& arg : block.arguments()) {
                const auto& slot = allocation.at(arg.get());
                if (!slot.is_weight) {
                    src << "    memcpy(" << cName(arg.get())
                        << ", inputs[" << input_idx << "], "
                        << slot.byte_size << ");\n";
                    ++input_idx;
                }
            }
            src << "\n";
        }

        // Emit each op.
        src << "    /* --- Op sequence --- */\n";
        bool had_error = false;
        std::string error_msg;
        block.walk([&](const sir::Operation* op) {
            if (had_error) return;
            auto res = emitOp(src, op, allocation, weights);
            if (!res) {
                had_error   = true;
                error_msg   = res.error().message;
            }
        });

        if (had_error)
            return std::unexpected(CodegenError{"codegen", error_msg});

        // Copy graph outputs from arena into the `outputs` array.
        {
            src << "\n    /* --- Copy outputs --- */\n";
            int out_idx = 0;
            // Outputs are the results of the last non-constant ops.
            block.walk([&](const sir::Operation* op) {
                if (op->mnemonic() == "sc_high.constant") return;
                // Identify "terminal" ops — those whose results have no users.
                for (size_t i = 0; i < op->numResults(); ++i) {
                    if (op->result(i)->hasNoUses()) {
                        const sir::Value* v    = op->result(i);
                        const auto&       slot = allocation.at(v);
                        src << "    memcpy(outputs[" << out_idx << "], "
                            << cName(v) << ", " << slot.byte_size << ");\n";
                        ++out_idx;
                    }
                }
            });
        }

        src << "}\n";
    }

    // --- model.h ---
    writeModelHeader(block);

    // --- weights.bin ---
    if (auto res = writeWeightsBin(weights); !res)
        return res;

    // --- arena_size.h ---
    // Determine total arena size from allocation map.
    size_t max_end = 0;
    for (const auto& [v, slot] : allocation)
        if (!slot.is_weight)
            max_end = std::max(max_end, slot.offset + slot.byte_size);
    writeArenaSizeHeader(max_end);

    utility::Logger::info(
        "CpuCCodegenTarget: wrote model.c + model.h + weights.bin + "
        "arena_size.h to '" + output_dir_.string() + "'");

    return {};
}

// =============================================================================
// Im2Col helper (static C function emitted into model.c)
//
// Layout convention: NCHW input, kernel [KH, KW], output [N, C*KH*KW, OH*OW].
// This is the standard Caffe im2col formulation.
// =============================================================================

void CpuCCodegenTarget::emitIm2ColHelper(std::ostream& os) {
    os << R"(
static void seecpp_im2col(
    const float* src,       /* [N, C, H, W] */
    float*       dst,       /* [N, C*KH*KW, OH*OW] */
    int N, int C, int H, int W,
    int KH, int KW,
    int stride_h, int stride_w,
    int pad_top, int pad_left, int pad_bottom, int pad_right,
    int dil_h, int dil_w)
{
    int OH = (H + pad_top + pad_bottom - dil_h*(KH-1) - 1) / stride_h + 1;
    int OW = (W + pad_left + pad_right - dil_w*(KW-1) - 1) / stride_w + 1;
    int col_rows = C * KH * KW;
    int col_cols = OH * OW;

    for (int n = 0; n < N; ++n) {
        float*       d_n = dst + n * col_rows * col_cols;
        const float* s_n = src + n * C * H * W;

        int col = 0;
        for (int c = 0; c < C; ++c) {
            for (int kh = 0; kh < KH; ++kh) {
                for (int kw = 0; kw < KW; ++kw) {
                    int row = (c * KH + kh) * KW + kw;
                    for (int oh = 0; oh < OH; ++oh) {
                        for (int ow = 0; ow < OW; ++ow) {
                            int ih = oh * stride_h - pad_top  + kh * dil_h;
                            int iw = ow * stride_w - pad_left + kw * dil_w;
                            int o  = oh * OW + ow;
                            d_n[row * col_cols + o] =
                                (ih >= 0 && ih < H && iw >= 0 && iw < W)
                                ? s_n[c * H * W + ih * W + iw]
                                : 0.0f;
                        }
                    }
                }
            }
        }
    }
}

)";
}

// =============================================================================
// Value pointer emission
// =============================================================================

std::string CpuCCodegenTarget::cName(const sir::Value* v) {
    // Strip SSA % prefix if present.
    std::string id(v->id());
    if (!id.empty() && id[0] == '%')
        id = id.substr(1);
    // Replace characters not valid in C identifiers.
    std::replace(id.begin(), id.end(), '.', '_');
    std::replace(id.begin(), id.end(), '-', '_');
    return "v_" + id;
}

std::string CpuCCodegenTarget::ptrExpr(const sir::Value*       v,
                                         const BufferAllocation& alloc,
                                         const std::string&      arena_var,
                                         const std::string&      weights_var) {
    const auto& slot = alloc.at(v);
    if (slot.is_weight) {
        // Weight: cast from the flat weight_blob at byte offset stored in
        // descriptor. We use the value id to look up position at runtime.
        // For simplicity in C codegen we encode the byte offset directly.
        return "(const float*)((const char*)" + weights_var +
               " + " + std::to_string(slot.offset) + "UL)";
    } else {
        return "(float*)((char*)" + arena_var +
               " + " + std::to_string(slot.offset) + "UL)";
    }
}

void CpuCCodegenTarget::emitValuePtr(std::ostream&           os,
                                      const sir::Value*       v,
                                      const BufferAllocation& alloc,
                                      const std::string&      arena_var,
                                      const std::string&      weights_var) {
    const auto& slot = alloc.at(v);
    const std::string qualifier = slot.is_weight ? "const float* " : "float* ";
    os << "    " << qualifier << cName(v) << " = "
       << ptrExpr(v, alloc, arena_var, weights_var) << ";\n";
}

// =============================================================================
// Op dispatch
// =============================================================================

std::expected<void, CodegenError>
CpuCCodegenTarget::emitOp(std::ostream&                os,
                            const sir::Operation*        op,
                            const BufferAllocation&      alloc,
                            const utility::WeightBuffer& weights) {
    const std::string mn(op->mnemonic());

    os << "\n    /* " << mn << " */\n";

    if (mn == "sc_high.constant") {
        // Constants live in WeightBuffer — no runtime code needed.
        return {};
    } else if (mn == "sc_low.im2col") {
        emitIm2ColOp(os, op, alloc);
    } else if (mn == "sc_low.matmul" || mn == "sc_low.gemm") {
        emitMatMulOp(os, op, alloc);
    } else if (mn == "sc_high.gemm") {
        emitGemmOp(os, op, alloc);
    } else if (mn == "sc_low.add" || mn == "sc_high.add") {
        emitAddOp(os, op, alloc);
    } else if (mn == "sc_high.relu" || mn == "sc_low.relu") {
        emitReluOp(os, op, alloc);
    } else if (mn == "sc_high.fused_ew") {
        emitFusedEwOp(os, op, alloc);
    } else if (mn == "sc_low.reshape") {
        // Reshape is a no-op in C — it's a logical reinterpretation.
        // The pointer already points to the same memory.
        os << "    /* sc_low.reshape: logical reinterpret, no copy needed */\n";
    } else if (mn == "sc_high.matmul") {
        emitMatMulOp(os, op, alloc);
    } else {
        return std::unexpected(CodegenError{
            "codegen",
            "CpuCCodegenTarget: unsupported op mnemonic '" + mn + "'"});
    }
    return {};
}

// =============================================================================
// Im2Col op
// =============================================================================

void CpuCCodegenTarget::emitIm2ColOp(std::ostream&           os,
                                       const sir::Operation*   op,
                                       const BufferAllocation& alloc) {
    const sir::Value* input  = op->operand(0);
    const sir::Value* output = op->result(0);

    const auto& in_dims = input->shape().dims;
    int N = (int)in_dims[0], C = (int)in_dims[1],
        H = (int)in_dims[2], W = (int)in_dims[3];

    auto kshape = op->getAttrAs<std::vector<int64_t>>("kernel_shape")
                      .value_or(std::vector<int64_t>{3, 3});
    auto strides = op->getAttrAs<std::vector<int64_t>>("strides")
                       .value_or(std::vector<int64_t>{1, 1});
    auto pads    = op->getAttrAs<std::vector<int64_t>>("pads")
                       .value_or(std::vector<int64_t>{0, 0, 0, 0});
    auto dilat   = op->getAttrAs<std::vector<int64_t>>("dilations")
                       .value_or(std::vector<int64_t>{1, 1});

    os << "    seecpp_im2col("
       << cName(input) << ", " << cName(output) << ",\n"
       << "        " << N << ", " << C << ", " << H << ", " << W << ",\n"
       << "        " << kshape[0] << ", " << kshape[1] << ",\n"
       << "        " << strides[0] << ", " << strides[1] << ",\n"
       << "        " << pads[0] << ", " << pads[1] << ", "
                     << pads[2] << ", " << pads[3] << ",\n"
       << "        " << dilat[0] << ", " << dilat[1] << ");\n";
}

// =============================================================================
// MatMul op — cblas_sgemm
//
// C = alpha * A * B + beta * C
// A: [M, K]  B: [K, N]  C: [M, N]
// For batched conv: A = filter_matrix [F, C*KH*KW]
//                   B = col_matrix    [C*KH*KW, OH*OW]
//                   C = output        [F, OH*OW]  per batch
// =============================================================================

void CpuCCodegenTarget::emitMatMulOp(std::ostream&           os,
                                      const sir::Operation*   op,
                                      const BufferAllocation& alloc) {
    const sir::Value* A   = op->operand(0);
    const sir::Value* B   = op->operand(1);
    const sir::Value* out = op->result(0);

    // A: [M, K], B: [K, N] (or batched [batch, K, N])
    const auto& a_dims = A->shape().dims;
    const auto& b_dims = B->shape().dims;

    // Handle batched case: emit a loop over batch dim.
    const bool batched = (b_dims.size() == 3);

    if (batched) {
        int64_t batch = b_dims[0];
        int64_t M     = a_dims[0];     // F (filters)
        int64_t K     = a_dims[1];     // C*KH*KW
        int64_t N_dim = b_dims[2];     // OH*OW

        os << "    for (int _b = 0; _b < " << batch << "; ++_b) {\n"
           << "        cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans,\n"
           << "            " << M << ", " << N_dim << ", " << K << ",\n"
           << "            1.0f,\n"
           << "            " << cName(A) << ", " << K << ",\n"
           << "            " << cName(B) << " + _b * " << (K * N_dim) << ", " << N_dim << ",\n"
           << "            0.0f,\n"
           << "            " << cName(out) << " + _b * " << (M * N_dim) << ", " << N_dim << ");\n"
           << "    }\n";
    } else {
        int64_t M     = a_dims[0];
        int64_t K     = a_dims[1];
        int64_t N_dim = b_dims[1];

        os << "    cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans,\n"
           << "        " << M << ", " << N_dim << ", " << K << ",\n"
           << "        1.0f,\n"
           << "        " << cName(A) << ", " << K << ",\n"
           << "        " << cName(B) << ", " << N_dim << ",\n"
           << "        0.0f,\n"
           << "        " << cName(out) << ", " << N_dim << ");\n";
    }

    // Fused Relu activation (stamped by OperatorFusionPass).
    const auto activation = op->getAttrAs<std::string>("activation");
    if (activation && *activation == "relu") {
        const int64_t total = out->shape().volume();
        os << "    /* fused relu activation */\n"
           << "    for (int _i = 0; _i < " << total << "; ++_i)\n"
           << "        " << cName(out) << "[_i] = "
           << cName(out) << "[_i] > 0.0f ? " << cName(out) << "[_i] : 0.0f;\n";
    }
}

// =============================================================================
// Gemm op — cblas_sgemm (with optional trans_a / trans_b and bias)
// =============================================================================

void CpuCCodegenTarget::emitGemmOp(std::ostream&           os,
                                    const sir::Operation*   op,
                                    const BufferAllocation& alloc) {
    const sir::Value* A   = op->operand(0);
    const sir::Value* B   = op->operand(1);
    const sir::Value* out = op->result(0);

    bool trans_a = op->getAttrAs<int64_t>("trans_a").value_or(0) != 0;
    bool trans_b = op->getAttrAs<int64_t>("trans_b").value_or(0) != 0;

    const auto& a_dims = A->shape().dims;
    const auto& b_dims = B->shape().dims;

    int64_t M = trans_a ? a_dims[1] : a_dims[0];
    int64_t K = trans_a ? a_dims[0] : a_dims[1];
    int64_t N = trans_b ? b_dims[0] : b_dims[1];

    os << "    cblas_sgemm(CblasRowMajor, "
       << (trans_a ? "CblasTrans" : "CblasNoTrans") << ", "
       << (trans_b ? "CblasTrans" : "CblasNoTrans") << ",\n"
       << "        " << M << ", " << N << ", " << K << ",\n"
       << "        1.0f,\n"
       << "        " << cName(A) << ", " << (trans_a ? M : K) << ",\n"
       << "        " << cName(B) << ", " << (trans_b ? K : N) << ",\n"
       << "        0.0f,\n"
       << "        " << cName(out) << ", " << N << ");\n";

    // Optional bias add.
    if (op->numOperands() >= 3) {
        const sir::Value* bias = op->operand(2);
        os << "    /* gemm bias add */\n"
           << "    for (int _i = 0; _i < " << M << "; ++_i)\n"
           << "        for (int _j = 0; _j < " << N << "; ++_j)\n"
           << "            " << cName(out) << "[_i * " << N << " + _j] += "
           << cName(bias) << "[_j];\n";
    }

    // Fused Relu.
    const auto activation = op->getAttrAs<std::string>("activation");
    if (activation && *activation == "relu") {
        const int64_t total = out->shape().volume();
        os << "    /* fused relu */\n"
           << "    for (int _i = 0; _i < " << total << "; ++_i)\n"
           << "        " << cName(out) << "[_i] = "
           << cName(out) << "[_i] > 0.0f ? " << cName(out) << "[_i] : 0.0f;\n";
    }
}

// =============================================================================
// Add op
// =============================================================================

void CpuCCodegenTarget::emitAddOp(std::ostream&           os,
                                   const sir::Operation*   op,
                                   const BufferAllocation& alloc) {
    const sir::Value* lhs = op->operand(0);
    const sir::Value* rhs = op->operand(1);
    const sir::Value* out = op->result(0);
    const int64_t total   = out->shape().volume();

    os << "    for (int _i = 0; _i < " << total << "; ++_i)\n"
       << "        " << cName(out) << "[_i] = "
       << cName(lhs) << "[_i] + " << cName(rhs) << "[_i];\n";
}

// =============================================================================
// Relu op
// =============================================================================

void CpuCCodegenTarget::emitReluOp(std::ostream&           os,
                                    const sir::Operation*   op,
                                    const BufferAllocation& alloc) {
    const sir::Value* input = op->operand(0);
    const sir::Value* out   = op->result(0);
    const int64_t total     = out->shape().volume();

    // In-place if input and output share the same arena slot (after DCE /
    // value forwarding). Otherwise copy-and-clamp.
    const auto& in_slot  = alloc.at(input);
    const auto& out_slot = alloc.at(out);

    if (in_slot.offset == out_slot.offset && !in_slot.is_weight) {
        os << "    for (int _i = 0; _i < " << total << "; ++_i)\n"
           << "        if (" << cName(out) << "[_i] < 0.0f) "
           << cName(out) << "[_i] = 0.0f;\n";
    } else {
        os << "    for (int _i = 0; _i < " << total << "; ++_i)\n"
           << "        " << cName(out) << "[_i] = "
           << cName(input) << "[_i] > 0.0f ? "
           << cName(input) << "[_i] : 0.0f;\n";
    }
}

// =============================================================================
// Fused elementwise op
// =============================================================================

void CpuCCodegenTarget::emitFusedEwOp(std::ostream&           os,
                                        const sir::Operation*   op,
                                        const BufferAllocation& alloc) {
    // op_sequence = "sc_high.add+sc_high.mul" etc.
    auto seq_attr = op->getAttrAs<std::string>("op_sequence")
                        .value_or("sc_high.add");

    const sir::Value* out   = op->result(0);
    const int64_t     total = out->shape().volume();

    // Build the innermost expression from the operands.
    // Convention: first two operands map to the first binary op in the sequence.
    // Additional operands fold into subsequent ops.
    os << "    for (int _i = 0; _i < " << total << "; ++_i) {\n"
       << "        float _acc = " << cName(op->operand(0)) << "[_i];\n";

    // Split op_sequence on '+' and fold remaining operands.
    size_t operand_idx = 1;
    size_t pos = 0;
    while (pos < seq_attr.size()) {
        size_t next = seq_attr.find('+', pos);
        std::string part = seq_attr.substr(
            pos, next == std::string::npos ? std::string::npos : next - pos);
        pos = (next == std::string::npos) ? seq_attr.size() : next + 1;

        if (part.find("add") != std::string::npos) {
            if (operand_idx < op->numOperands())
                os << "        _acc += " << cName(op->operand(operand_idx++))
                   << "[_i];\n";
        } else if (part.find("mul") != std::string::npos) {
            if (operand_idx < op->numOperands())
                os << "        _acc *= " << cName(op->operand(operand_idx++))
                   << "[_i];\n";
        } else if (part.find("relu") != std::string::npos) {
            os << "        if (_acc < 0.0f) _acc = 0.0f;\n";
        } else if (part.find("sub") != std::string::npos) {
            if (operand_idx < op->numOperands())
                os << "        _acc -= " << cName(op->operand(operand_idx++))
                   << "[_i];\n";
        } else if (part.find("div") != std::string::npos) {
            if (operand_idx < op->numOperands())
                os << "        _acc /= " << cName(op->operand(operand_idx++))
                   << "[_i];\n";
        }
    }
    os << "        " << cName(out) << "[_i] = _acc;\n"
       << "    }\n";
}

// =============================================================================
// Auxiliary file writers
// =============================================================================

std::expected<void, CodegenError>
CpuCCodegenTarget::writeWeightsBin(const utility::WeightBuffer& weights) {
    std::ofstream bin(output_dir_ / "weights.bin", std::ios::binary);
    if (!bin)
        return std::unexpected(CodegenError{
            "codegen", "Cannot open weights.bin for writing"});

    weights.forEach([&](std::string_view /*key*/,
                         std::span<const uint8_t> raw) {
        bin.write(reinterpret_cast<const char*>(raw.data()),
                  static_cast<std::streamsize>(raw.size()));
    });
    return {};
}

void CpuCCodegenTarget::writeArenaSizeHeader(size_t arena_bytes) {
    std::ofstream h(output_dir_ / "arena_size.h");
    h << "/* AUTO-GENERATED by SeeC++ CpuCCodegenTarget */\n"
      << "#pragma once\n"
      << "#include <stddef.h>\n"
      << "static const size_t SEECPP_ARENA_BYTES = " << arena_bytes << "UL;\n";
}

void CpuCCodegenTarget::writeModelHeader(const sir::Block& block) {
    std::ofstream h(output_dir_ / "model.h");
    h << "/* AUTO-GENERATED by SeeC++ CpuCCodegenTarget */\n"
      << "#pragma once\n"
      << "#include <stddef.h>\n\n"
      << "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"
      << "/**\n"
      << " * Run the compiled SeeC++ model.\n"
      << " *\n"
      << " * @param inputs      Array of input tensor pointers (float32, NCHW).\n"
      << " * @param outputs     Array of output tensor pointers (caller-allocated).\n"
      << " * @param arena       Scratch buffer of SEECPP_ARENA_BYTES bytes.\n"
      << " * @param weight_blob Flat weight binary loaded from weights.bin.\n"
      << " */\n"
      << "void seecpp_run_model(\n"
      << "    const float* const* inputs,\n"
      << "    float**             outputs,\n"
      << "    void*               arena,\n"
      << "    const void*         weight_blob);\n\n"
      << "#ifdef __cplusplus\n} /* extern \"C\" */\n#endif\n";
}

} // namespace seecpp::backend