#include "frontend/onnx_ingressor.hpp"
#include "include/utility/logger.hpp"
#include "include/utility/weight_buffer.hpp"

#include <onnx.pb.h>   // Generated by protoc
#include <fstream>
#include <sstream>

namespace seecpp::frontend {

// External global weight buffer (linker-provided by the embedding translation
// unit). Weights are stored by ONNX initializer name and consumed downstream
// by the code-generation backend.
extern utility::WeightBuffer global_weight_buffer;

// =============================================================================
// Handler dispatch table
// =============================================================================
// Each entry maps an ONNX op_type string to a translation lambda.
// Adding a new op = adding one entry here. No touch to processNodes needed.
// Pattern mirrors torch-mlir's OnnxToTorch op registry.
// =============================================================================

const std::unordered_map<std::string, OnnxIngressor::NodeHandler>
OnnxIngressor::kHandlers = {

    // --- Convolution --------------------------------------------------------
    {"Conv", [](const onnx::NodeProto& node,
                SymbolTable& sym,
                sir::Block&  block) -> std::expected<sir::Operation*, IngestError> {

        Value* input  = sym.count(node.input(0)) ? sym.at(node.input(0)) : nullptr;
        Value* filter = sym.count(node.input(1)) ? sym.at(node.input(1)) : nullptr;
        Value* bias   = (node.input_size() > 2 && sym.count(node.input(2)))
                            ? sym.at(node.input(2)) : nullptr;

        if (!input || !filter)
            return std::unexpected(IngestError{
                node.name(), "Conv: missing input or filter in symbol table"});

        // Extract strides / pads / dilations / group from ONNX attributes.
        std::vector<int64_t> strides   = {1, 1};
        std::vector<int64_t> pads      = {0, 0, 0, 0};
        std::vector<int64_t> dilations = {1, 1};
        int64_t              group     = 1;

        for (const auto& attr : node.attribute()) {
            if (attr.name() == "strides")
                strides.assign(attr.ints().begin(), attr.ints().end());
            else if (attr.name() == "pads")
                pads.assign(attr.ints().begin(), attr.ints().end());
            else if (attr.name() == "dilations")
                dilations.assign(attr.ints().begin(), attr.ints().end());
            else if (attr.name() == "group")
                group = attr.i();
        }

        auto op = sir::OpBuilder::conv2d(
            input, filter, bias, strides, pads, dilations, group);
        return block.appendOp(std::move(op));
    }},

    // --- Batch Normalisation ------------------------------------------------
    {"BatchNormalization", [](const onnx::NodeProto& node,
                              SymbolTable& sym,
                              sir::Block&  block) -> std::expected<sir::Operation*, IngestError> {

        // ONNX BN has exactly 5 inputs: X, scale, B, mean, var.
        if (node.input_size() < 5)
            return std::unexpected(IngestError{
                node.name(), "BatchNormalization: expected 5 inputs"});

        auto lookup = [&](int i) -> sir::Value* {
            const auto& name = node.input(i);
            return sym.count(name) ? sym.at(name) : nullptr;
        };

        auto* input = lookup(0); auto* scale = lookup(1);
        auto* bias  = lookup(2); auto* mean  = lookup(3);
        auto* var   = lookup(4);

        if (!input || !scale || !bias || !mean || !var)
            return std::unexpected(IngestError{
                node.name(), "BatchNormalization: one or more inputs missing"});

        float epsilon = 1e-5f;
        for (const auto& attr : node.attribute())
            if (attr.name() == "epsilon") epsilon = attr.f();

        auto op = sir::OpBuilder::batchNorm(input, scale, bias, mean, var, epsilon);
        return block.appendOp(std::move(op));
    }},

    // --- Gemm / MatMul ------------------------------------------------------
    {"Gemm", [](const onnx::NodeProto& node,
                SymbolTable& sym,
                sir::Block&  block) -> std::expected<sir::Operation*, IngestError> {

        Value* A    = sym.count(node.input(0)) ? sym.at(node.input(0)) : nullptr;
        Value* B    = sym.count(node.input(1)) ? sym.at(node.input(1)) : nullptr;
        Value* bias = (node.input_size() > 2 && sym.count(node.input(2)))
                          ? sym.at(node.input(2)) : nullptr;

        if (!A || !B)
            return std::unexpected(IngestError{node.name(), "Gemm: missing A or B"});

        bool trans_a = false, trans_b = false;
        for (const auto& attr : node.attribute()) {
            if (attr.name() == "transA") trans_a = attr.i() != 0;
            if (attr.name() == "transB") trans_b = attr.i() != 0;
        }

        auto op = sir::OpBuilder::gemm(A, B, bias, trans_a, trans_b);
        return block.appendOp(std::move(op));
    }},

    // --- Relu ---------------------------------------------------------------
    {"Relu", [](const onnx::NodeProto& node,
                SymbolTable& sym,
                sir::Block&  block) -> std::expected<sir::Operation*, IngestError> {

        if (node.input_size() < 1)
            return std::unexpected(IngestError{node.name(), "Relu: no input"});

        auto* input = sym.count(node.input(0)) ? sym.at(node.input(0)) : nullptr;
        if (!input)
            return std::unexpected(IngestError{node.name(), "Relu: input not in symbol table"});

        auto op = sir::OpBuilder::relu(input);
        return block.appendOp(std::move(op));
    }},
};

// =============================================================================
// Public API
// =============================================================================

[[nodiscard]]
std::expected<std::unique_ptr<sir::Block>, IngestError>
OnnxIngressor::ingest(std::string_view model_path) {

    current_model_path_ = std::string(model_path);
    utility::Logger::info("Loading ONNX model from: " + current_model_path_);

    // --- 1. Read file into memory ------------------------------------------
    std::ifstream file(current_model_path_, std::ios::ate | std::ios::binary);
    if (!file) {
        return std::unexpected(IngestError{
            "", "Could not open model file: " + current_model_path_});
    }

    const std::streamsize file_size = file.tellg();
    file.seekg(0, std::ios::beg);

    std::vector<char> raw(static_cast<size_t>(file_size));
    if (!file.read(raw.data(), file_size)) {
        return std::unexpected(IngestError{
            "", "Failed to read model file: " + current_model_path_});
    }

    // --- 2. Deserialise protobuf -------------------------------------------
    onnx::ModelProto model;
    if (!model.ParseFromArray(raw.data(), static_cast<int>(file_size))) {
        return std::unexpected(IngestError{
            "", "Failed to parse ONNX protobuf: " + current_model_path_});
    }

    const auto& graph = model.graph();

    // --- 3. Build the SIR Block --------------------------------------------
    // The block is constructed here; ownership is returned to the caller.
    auto block = std::make_unique<sir::Block>();
    SymbolTable sym;

    processInitializers(graph, sym, *block);
    processInputs(graph, sym, *block);

    if (auto result = processNodes(graph, sym, *block); !result) {
        return std::unexpected(result.error());
    }

    utility::Logger::info(
        "Ingested " + std::to_string(block->numOps()) +
        " operations from " + current_model_path_);

    return block;
}

// =============================================================================
// Private helpers
// =============================================================================

void OnnxIngressor::processInitializers(
    const onnx::GraphProto& graph,
    SymbolTable&            sym,
    sir::Block&             block)
{
    for (const auto& init : graph.initializer()) {
        // Map ONNX dtype -> SIR dtype. Fall back to F32 for unsupported types.
        auto dt = mapDataType(init.data_type()).value_or(sir::DataType::F32);

        sir::Shape shape;
        for (auto d : init.dims()) shape.dims.push_back(d);

        // Constant op: no operands, one result whose name matches the
        // initializer so downstream nodes can look it up by name.
        auto* op = block.appendOp("sc_high.constant");
        sym[init.name()] = op->addResult(init.name(), dt, shape);

        // Persist raw float data in the weight buffer for the codegen backend.
        // raw_data() is preferred over float_data() as it covers all dtypes.
        if (!init.raw_data().empty()) {
            const float* ptr = reinterpret_cast<const float*>(init.raw_data().data());
            std::vector<float> data(ptr, ptr + shape.volume());
            global_weight_buffer.addWeight(init.name(), std::move(data));
        } else if (!init.float_data().empty()) {
            std::vector<float> data(init.float_data().begin(),
                                    init.float_data().end());
            global_weight_buffer.addWeight(init.name(), std::move(data));
        }
    }
}

void OnnxIngressor::processInputs(
    const onnx::GraphProto& graph,
    SymbolTable&            sym,
    sir::Block&             block)
{
    for (const auto& input_proto : graph.input()) {
        // Initializers already have entries in sym — skip them.
        if (sym.count(input_proto.name())) continue;

        const auto& type_proto = input_proto.type().tensor_type();
        auto dt = mapDataType(type_proto.elem_type()).value_or(sir::DataType::F32);

        sir::Shape shape;
        if (type_proto.has_shape()) {
            for (const auto& dim : type_proto.shape().dim()) {
                // dim_value == 0 usually means dynamic batch in ONNX.
                shape.dims.push_back(
                    dim.has_dim_value() && dim.dim_value() > 0
                        ? dim.dim_value()
                        : sir::Shape::kDynamic);
            }
        }

        // Block argument: a Value with no defining op, representing a
        // live-in tensor (model input / dynamic placeholder).
        sym[input_proto.name()] = block.addArgument(dt, shape);
    }
}

[[nodiscard]]
std::expected<void, IngestError> OnnxIngressor::processNodes(
    const onnx::GraphProto& graph,
    SymbolTable&            sym,
    sir::Block&             block)
{
    for (const auto& node : graph.node()) {
        const std::string& op_type = node.op_type();

        auto it = kHandlers.find(op_type);
        if (it == kHandlers.end()) {
            // Unknown op: emit a passthrough placeholder tagged with the
            // original ONNX op_type so later passes can identify and lower it.
            utility::Logger::warn(
                "Unhandled ONNX op '" + op_type +
                "' — emitting sc_high.unknown passthrough");

            auto* sir_op = block.appendOp("sc_high.unknown");
            sir_op->setAttribute("onnx_op_type", op_type);

            for (const auto& in_name : node.input())
                if (sym.count(in_name))
                    sir_op->addOperand(sym.at(in_name));

            for (const auto& out_name : node.output()) {
                sym[out_name] = sir_op->addResult(
                    out_name, sir::DataType::F32, sir::Shape{});
            }
            continue;
        }

        // Dispatch to the registered handler.
        auto result = it->second(node, sym, block);
        if (!result)
            return std::unexpected(result.error());

        sir::Operation* sir_op = *result;

        // Wire the new op's results back into the symbol table so subsequent
        // nodes can find them by their ONNX output tensor names.
        for (int i = 0; i < node.output_size() && i < (int)sir_op->numResults(); ++i)
            sym[node.output(i)] = sir_op->result(i);
    }

    return {};  // success
}

// =============================================================================
// DataType mapping
// =============================================================================
// ONNX TensorProto::DataType enum values (from onnx.proto):
//   FLOAT=1  UINT8=2  INT8=3  UINT16=4  INT16=5  INT32=6  INT64=7
//   STRING=8 BOOL=9  FLOAT16=10 DOUBLE=11 UINT32=12 UINT64=13
//   COMPLEX64=14 COMPLEX128=15 BFLOAT16=16
// =============================================================================

[[nodiscard]]
std::optional<sir::DataType> OnnxIngressor::mapDataType(int onnx_type) {
    switch (onnx_type) {
        case 1:  return sir::DataType::F32;
        case 3:  return sir::DataType::I8;
        case 6:  return sir::DataType::I32;
        case 7:  return sir::DataType::I64;
        case 9:  return sir::DataType::Bool;
        case 10: return sir::DataType::F16;
        case 11: return sir::DataType::F64;
        case 16: return sir::DataType::BF16;
        default: return std::nullopt;   // caller decides fallback
    }
}

} // namespace seecpp::frontend