#include "frontend/onnx_ingressor.hpp"
#include "include/utility/logger.hpp"
#include "include/utility/weight_buffer.hpp"
#include <fstream>
#include <onnx.pb.h> // Generated by protoc

namespace seecpp::frontend {

// External global buffer for weights (as discussed in rigor check)
extern utility::WeightBuffer global_weight_buffer;

bool OnnxIngressor::ingest(const std::string& model_path, sir::Block& block) {
    utility::Logger::info("Loading ONNX model from: " + model_path);

    // 1. Load the Protobuf from disk
    onnx::ModelProto model;
    std::ifstream input(model_path, std::ios::ate | std::ios::binary);
    if (!input) {
        utility::Logger::error("Could not open model file.");
        return false;
    }

    std::streamsize size = input.tellg();
    input.seekg(0, std::ios::beg);
    std::vector<char> buffer(size);
    if (!input.read(buffer.data(), size)) {
        utility::Logger::error("Failed to read model file.");
        return false;
    }

    if (!model.ParseFromArray(buffer.data(), size)) {
        utility::Logger::error("Failed to parse ONNX Protobuf.");
        return false;
    }

    const auto& graph = model.graph();

    // 2. Process Initializers (Weights) -> Turn into sc_high.constant
    processInitializers(graph, block);

    // 3. Process Graph Inputs (Placeholders)
    for (const auto& input_proto : graph.input()) {
        // If it's already in symbol_table, it's an initializer, skip it
        if (symbol_table.count(input_proto.name())) continue;

        // Otherwise, it's a model input (like an image)
        auto* op = block.appendOp("sc_high.input");
        sir::Shape shape;
        for (auto dim : input_proto.type().tensor_type().shape().dim()) {
            shape.dims.push_back(dim.dim_value());
        }
        symbol_table[input_proto.name()] = op->addResult(input_proto.name(), sir::DataType::F32, shape);
    }

    // 4. Process Nodes (The actual computation)
    processNodes(graph, block);

    utility::Logger::info("Successfully ingested " + std::to_string(block.operations.size()) + " operations.");
    return true;
}

void OnnxIngressor::processInitializers(const onnx::GraphProto& graph, sir::Block& block) {
    for (const auto& init : graph.initializer()) {
        // Create a constant op
        auto* op = block.appendOp("sc_high.constant");
        
        // Populate SIR Shape
        sir::Shape shape;
        for (auto d : init.dims()) shape.dims.push_back(d);

        // Store weight in our WeightBuffer utility
        // Note: For brevity, we assume FLOAT data here
        std::vector<float> data(init.float_data().begin(), init.float_data().end());
        global_weight_buffer.addWeight(init.name(), data);

        // Map it in the symbol table
        symbol_table[init.name()] = op->addResult(init.name(), sir::DataType::F32, shape);
    }
}

void OnnxIngressor::processNodes(const onnx::GraphProto& graph, sir::Block& block) {
    for (const auto& node : graph.node()) {
        // Map ONNX Op to SeeC++ Op
        std::string op_name = "sc_high." + node.op_type();
        auto* sir_op = block.appendOp(op_name);

        // Map Inputs
        for (const auto& in_name : node.input()) {
            if (symbol_table.count(in_name)) {
                sir_op->addOperand(symbol_table[in_name]);
            }
        }

        // Create Results
        for (const auto& out_name : node.output()) {
            symbol_table[out_name] = sir_op->addResult(out_name, sir::DataType::F32, {});
        }
    }
}

} // namespace seecpp::frontend